### ISSUE TITLE
Update with SotM Africa 2025

### ISSUE THREAD

**Issue by jeafreezy** [osmafrica/stateofthemap.africa#11]
Hi @enockseth,

Dar es Salaam, Tanzania has been selected as the venue for the SotM Africa 2025. We'll need to update the website with the information. Here are the details:

- Date:  5 December - 7 December 2025.
- Venue: Dar es Salaam, Tanzania.
- Logo:  @kateregga1 kindly help with the logo.

Once the logo is available, I will open a PR.

ref: https://wiki.openstreetmap.org/wiki/State_of_the_Map_Africa_2025

**Comment by kateregga1** [comment]
![SotM_Africa_2025_Logo](https://github.com/user-attachments/assets/8c8a7283-ed31-4023-8eae-f330cb3526b7)

Here is the logo @jeafreezy

**Comment by enockseth** [comment]
Hi @jeafreezy, you have been added to this org. Please go ahead :). Cheers!

**Comment by jeafreezy** [comment]
Thanks @kateregga1. PR opened in #12 @enockseth.

**Comment by enockseth** [comment]
@jeafreezy Please kindly proceed to merge PRs anytime, I will also try to review whenever possible :)

**Comment by jeafreezy** [comment]
@enockseth , alright, noted. Thanks.
